- name: Variable demo
  hosts: localhost
  connection: local
  vars:
    a: 342
  tasks:
    - name: print variable - task level
      vars:
        a: 400
      ansible.builtin.debug:
         msg: a -{{a}}
