## variables precedence
# 1. first priority cli (command line) declaration
# 2. Task level variable
# 2. then play level

- name: Variable demo
  hosts: localhost
  connection: local
  vars:
    a: 100
    roles:
      - sample
    tasks:
      - name: Print Variable
        ansible.builtin.debug:
         msg: a - {{ a }}
      - name: Print Variable - task level
        vars:
        a: 200
        ansible.builtin.debug:
         msg: a - {{ a }}
