- name: Variable types
  hosts: localhost
  connection: local
  vars:
    x: 100
    my_boolean: true
  tasks:
    - name: Conditional
      ansible.builtin.debug:
        msg: OK
        when: x > 200

    - name: print boolean
      ansible.builtin.debug:
        msg: go ahead
        when: my_boolean