- name: sample
  hosts: all
  tasks:
    - name: Shell
      ansible.builtin.shell: sleep 30

# One node at a time:  ansible-playbook -i inv3 -e ansible_user=ec2-user -e ansible_password=DevOps321 -f 1 08-parallelism.yml
# ten node at a time:  ansible-playbook -i inv3 -e ansible_user=ec2-user -e ansible_password=DevOps321 -f 10 08-parallelism.yml